export const data = [
  {
    question: "Who is known as the 'God of Cricket'?",
    option1: "Sachin Tendulkar",
    option2: "Virat Kohli",
    option3: "Rahul Dravid",
    option4: "MS Dhoni",
    ans: 1,
  },
  {
    question: "Which player has the highest number of centuries in One Day Internationals (ODIs)?",
    option1: "Sachin Tendulkar",
    option2: "Rohit Sharma",
    option3: "Virat Kohli",
    option4: "AB de Villiers",
    ans: 1,
  },
  {
    question: "Which team has won the most ICC Cricket World Cups?",
    option1: "India",
    option2: "Australia",
    option3: "West Indies",
    option4: "England",
    ans: 2,
  },
  {
    question: "Who has scored the fastest century in T20 International cricket?",
    option1: "Chris Gayle",
    option2: "Yuvraj Singh",
    option3: "Rohit Sharma",
    option4: "David Miller",
    ans: 1,
  },
  {
    question: "Which bowler has taken the most wickets in Test cricket?",
    option1: "Muttiah Muralitharan",
    option2: "Shane Warne",
    option3: "Anil Kumble",
    option4: "James Anderson",
    ans: 1,
  },
];
